---
- hosts: all
  tasks:
  - name: ansible create directory example
    file:
      path: /tmp/devops_directory
      state: directory
- hosts: all
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest